"use client";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogClose,
} from "@/components/ui/dialog";

interface DisclaimerDialogProps {
  disclaimerOpen: boolean;
  setDisclaimerOpen: (open: boolean) => void;
}

export const DisclaimerDialog: React.FC<DisclaimerDialogProps> = ({
  disclaimerOpen,
  setDisclaimerOpen,
}) => {
  return (
    <Dialog open={disclaimerOpen} onOpenChange={setDisclaimerOpen}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Disclaimer</DialogTitle>
        </DialogHeader>
        <div className="space-y-4 text-sm text-white/70">
          <p>
            Pyro Plot is provided for informational and planning purposes only.
            It is not a substitute for professional consultation, legal
            guidance, or safety training.
          </p>
          <p>
            All calculations and visualizations generated by Pyro Plot are based
            on generally accepted guidelines (including NFPA 1123
            recommendations of 70 ft per inch of shell diameter, or 100 ft per
            inch of shell diameter) and other commonly referenced standards.
            However, fireworks regulations vary by state, county, city, and site
            conditions. You must always confirm requirements with, and obtain
            approval from, your local Authority Having Jurisdiction (AHJ) before
            conducting any fireworks display. Local laws, site-specific
            geography, and weather conditions may override or alter these
            guidelines.
          </p>
          <p>
            Pyro Plot does not guarantee accuracy, completeness, or compliance
            with applicable laws. By using this tool, you acknowledge that you
            assume full responsibility for how the information is applied. Pyro
            Plot and its creators disclaim any liability for damages, injuries,
            fines, or legal consequences resulting from the use or misuse of
            this information.
          </p>
          <div>
            <p className="font-semibold mb-2 text-white">Important:</p>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>Always follow federal, state, and local regulations.</li>
              <li>
                Consult with licensed display operators and professionals.
              </li>
              <li>Prioritize safety at all times.</li>
              <li>
                Never use this tool as your sole source for display planning.
              </li>
            </ul>
          </div>
          <p>
            By using Pyro Plot, you agree to these terms and understand that the
            tool is intended only as a planning aid, not an authoritative guide.
          </p>
        </div>
        <DialogFooter>
          <DialogClose asChild>
            <button
              type="button"
              className="inline-flex items-center justify-center rounded-md border border-border bg-background px-3 py-2 text-sm hover:bg-muted"
            >
              I Understand
            </button>
          </DialogClose>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
