"use client";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogClose,
} from "@/components/ui/dialog";

interface MapProps {
  mapContainerRef: React.RefObject<HTMLDivElement | null>;
  handleMapDrop: (e: React.DragEvent<HTMLDivElement>) => void;
  handleMapDragOver: (e: React.DragEvent<HTMLDivElement>) => void;
  disclaimerOpen: boolean;
  setDisclaimerOpen: (open: boolean) => void;
  helpOpen: boolean;
  setHelpOpen: (open: boolean) => void;
  safetyDistance: 70 | 100;
}

export const Map: React.FC<MapProps> = ({
  mapContainerRef,
  handleMapDrop,
  handleMapDragOver,
  disclaimerOpen,
  setDisclaimerOpen,
  helpOpen,
  setHelpOpen,
  safetyDistance,
}) => {
  return (
    <>
      <div className="flex-1">
        <div
          ref={mapContainerRef}
          className="h-full w-full"
          onDrop={handleMapDrop}
          onDragOver={handleMapDragOver}
        />
      </div>

      <Dialog open={disclaimerOpen} onOpenChange={setDisclaimerOpen}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Disclaimer</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 text-sm text-white/70">
            <p>
              Pyro Plot is provided for informational and planning purposes
              only. It is not a substitute for professional consultation, legal
              guidance, or safety training.
            </p>
            <p>
              All calculations and visualizations generated by Pyro Plot are
              based on generally accepted guidelines (including NFPA 1123
              recommendations of {safetyDistance} ft per inch of shell diameter)
              and other commonly referenced standards. However, fireworks
              regulations vary by state, county, city, and site conditions. You
              must always confirm requirements with, and obtain approval from,
              your local Authority Having Jurisdiction (AHJ) before conducting
              any fireworks display. Local laws, site-specific geography, and
              weather conditions may override or alter these guidelines.
            </p>
            <p>
              Pyro Plot does not guarantee accuracy, completeness, or compliance
              with applicable laws. By using this tool, you acknowledge that you
              assume full responsibility for how the information is applied.
              Pyro Plot and its creators disclaim any liability for damages,
              injuries, fines, or legal consequences resulting from the use or
              misuse of this information.
            </p>
            <div>
              <p className="font-semibold mb-2 text-white">Important:</p>
              <ul className="list-disc list-inside space-y-1 ml-2">
                <li>Always follow federal, state, and local regulations.</li>
                <li>
                  Consult with licensed display operators and professionals.
                </li>
                <li>Prioritize safety at all times.</li>
                <li>
                  Never use this tool as your sole source for display planning.
                </li>
              </ul>
            </div>
            <p>
              By using Pyro Plot, you agree to these terms and understand that
              the tool is intended only as a planning aid, not an authoritative
              guide.
            </p>
          </div>
          <DialogFooter>
            <DialogClose asChild>
              <button
                type="button"
                className="inline-flex items-center justify-center rounded-md border border-border bg-background px-3 py-2 text-sm hover:bg-muted"
              >
                I Understand
              </button>
            </DialogClose>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Floating Action Button */}
      <button
        type="button"
        onClick={() => setHelpOpen(true)}
        className="fixed bottom-6 right-6 z-50 w-14 h-14 rounded-full bg-brand text-black flex items-center justify-center shadow-lg hover:scale-105 hover:shadow-xl transition-all duration-200 ease-in-out"
        aria-label="Open help"
      >
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
        >
          <circle cx="12" cy="12" r="10" />
          <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
          <path d="M12 17h.01" />
        </svg>
      </button>

      {/* Help Dialog */}
      <Dialog open={helpOpen} onOpenChange={setHelpOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>How to Use Pyro Plot</DialogTitle>
            <DialogDescription>
              Learn the controls and actions available in the application
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="overflow-hidden border border-border rounded-lg">
              <table className="w-full">
                <thead className="bg-muted">
                  <tr>
                    <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground">
                      Action
                    </th>
                    <th className="px-4 py-3 text-left text-sm font-medium text-muted-foreground">
                      Description
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  <tr>
                    <td className="px-4 py-3 text-sm font-medium">Pan Map</td>
                    <td className="px-4 py-3 text-sm text-muted-foreground">
                      Left-click and drag to move around the map
                    </td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 text-sm font-medium">
                      Rotate Map
                    </td>
                    <td className="px-4 py-3 text-sm text-muted-foreground">
                      Right-click and drag to rotate the map view
                    </td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 text-sm font-medium">Zoom</td>
                    <td className="px-4 py-3 text-sm text-muted-foreground">
                      Scroll wheel to zoom in and out
                    </td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 text-sm font-medium">
                      Add Annotation
                    </td>
                    <td className="px-4 py-3 text-sm text-muted-foreground">
                      Drag annotation from sidebar and drop on map
                    </td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 text-sm font-medium">
                      Move Annotation
                    </td>
                    <td className="px-4 py-3 text-sm text-muted-foreground">
                      Click and drag annotation label to reposition
                    </td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 text-sm font-medium">
                      Resize Area
                    </td>
                    <td className="px-4 py-3 text-sm text-muted-foreground">
                      Drag corner markers to resize audience/restricted areas
                    </td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 text-sm font-medium">
                      Adjust Measurement
                    </td>
                    <td className="px-4 py-3 text-sm text-muted-foreground">
                      Drag measurement points to change distance
                    </td>
                  </tr>
                  <tr>
                    <td className="px-4 py-3 text-sm font-medium">
                      Delete Annotation
                    </td>
                    <td className="px-4 py-3 text-sm text-muted-foreground">
                      Right-click on annotation label to remove
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <DialogFooter>
            <DialogClose asChild>
              <button
                type="button"
                className="inline-flex items-center justify-center rounded-md border border-border bg-background px-3 py-2 text-sm hover:bg-muted"
              >
                Got it
              </button>
            </DialogClose>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
};
